<a href="https://colab.research.google.com/github/shreevatsakashyap/Calculator/blob/ml/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.11.0'

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y= dataset.iloc[:,-1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

**initializing  ANN as sequence of layers**




In [ ]:
from keras.engine.sequential import Sequential
ann = Sequential()

**adding the new ip layer and the hidden layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

**second hl**

In [ ]:
ann.add(tf.keras.layers.Dense(units=7,activation='relu'))

**op layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

**training the ann**

**compiling the ann**

In [ ]:
ann.compile(optimizer = 'adam',loss= 'binary_crossentropy',metrics=['accuracy'])

**training the ann on training set**

In [ ]:
ann.fit(X_train,y_train,batch_size = 15 , epochs = 120)

Epoch 1/120
534/534 [==============================] - 2s 2ms/step - loss: 0.5652 - accuracy: 0.7336
Epoch 2/120
534/534 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.7960
Epoch 3/120
534/534 [==============================] - 1s 2ms/step - loss: 0.4289 - accuracy: 0.8049
Epoch 4/120
534/534 [==============================] - 1s 2ms/step - loss: 0.3965 - accuracy: 0.8356
Epoch 5/120
534/534 [==============================] - 1s 2ms/step - loss: 0.3725 - accuracy: 0.8432
Epoch 6/120
534/534 [==============================] - 1s 3ms/step - loss: 0.3624 - accuracy: 0.8489
Epoch 7/120
534/534 [==============================] - 1s 2ms/step - loss: 0.3570 - accuracy: 0.8497
Epoch 8/120
534/534 [==============================] - 1s 2ms/step - loss: 0.3531 - accuracy: 0.8515
Epoch 9/120
534/534 [==============================] - 1s 2ms/step - loss: 0.3506 - accuracy: 0.8537
Epoch 10/120
534/534 [==============================] - 1s 2ms/step - loss: 0.3490 - accura

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 97ms/step
[[False]]


In [ ]:
y_pred = ann.predict(X_test)
y_pred =(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1522   73]
 [ 199  206]]


0.864